# Generated by Django 3.1.7 on 2022-03-20 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220319_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
