# Generated by Django 3.1.7 on 2022-03-20 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220320_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
